export const DEFAULT_COLORS_LIST = [
  "#FF8000",
  "#FF0004",
  "#FF00BF",
  "#9DFF00",
  "#00FFB7",
  "#FFFFFF",
  "#FFE100",
  "#003CFF",
] as const;

export const COLOR_PRIMARY = DEFAULT_COLORS_LIST[7];
export const COLOR_SUCCESS = DEFAULT_COLORS_LIST[3];
export const COLOR_DESTRUCTIVE = DEFAULT_COLORS_LIST[1];
