export type THostEvents =
  | "game_started"
  | "round_1_start"
  | "round_2_start"
  | "final_round_start"
  | "general_round_end"
  | "question_table_open"
  | "question_selected"
  | "question_answered"
  | "regular_question_open"
  | "regular_question_answer_start"
  | "regular_correct_answer"
  | "regular_incorrect_answer"
  | "regular_timeout"
  | "all_players_incorrect"
  | "cat_in_bag_open"
  | "cat_in_bag_modal"
  | "cat_in_bag_player_selected"
  | "cat_in_bag_answer_start"
  | "cat_in_bag_correct"
  | "cat_in_bag_incorrect"
  | "auction_open"
  | "auction_modal"
  | "auction_bet_placed"
  | "auction_bet_all"
  | "auction_pass"
  | "auction_winner"
  | "auction_question_start"
  | "auction_correct_answer"
  | "auction_incorrect_answer"
  | "final_round_start"
  | "final_bet_placed"
  | "final_all_bets_placed"
  | "final_player_turn"
  | "final_answer_start"
  | "final_entered_answer"
  | "final_results"
  | "player_selected"
  | "timer_warning"
  | "timer_expired"
  | "game_results";

export interface IHostPhrase {
  id: string;
  eventType: THostEvents;
  label: string;
}
